DATASETS:
  NAMES: ("market1501",)
  TEST_NAMES: 'market1501'

DATALOADER:
  SAMPLER: 'softmax'

SOLVER:
  OPT: 'adam'
  LOSSTYPE: ('softmax',)
  MAX_EPOCHS: 100
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [30, 55, 80]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 256



