MODEL:
  BACKBONE: "resnet50"
  GCB:
    ratio: 0.0625


DATASETS:
  NAMES: ('market1501',)
  TEST_NAMES: "market1501"

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4 # 4 for paper & 3 for competition1910

SOLVER:
  OPT: "adam"
  LOSSTYPE: ('softmax', 'triplet')
  MAX_EPOCHS: 100 # old 120
  BASE_LR: 0.0004
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64 # old 64

  STEPS: [40, 70] # old [40, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  #EVAL_PERIOD: 1 # old 30
  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 32
  WEIGHT: ""



